name: Build qmk on GitHub Actions

on:
  - push

env:
  KEYBOARD: 'kewbie/kewbie46'
  KEYMAP: 'via'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#    - name: Clone qmk/qmk_firmware
    - name: Clone higemaru/qmk_firmware
      uses: actions/checkout@v3
      with:
#        repository: 'qmk/qmk_firmware'
        repository: 'higemaru/qmk_firmware'
        submodules: true
    - name: Install dependencies
      run: ./util/qmk_install.sh
    - name: Install qmk cli
      run: python3 -m pip install --user qmk
    - name: set path
      run: echo 'PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc && source $HOME/.bashrc
    - name: build
      run: qmk compile -kb ${{ env.KEYBOARD }} -km ${{ env.KEYMAP }}
    - uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: ./.build/*.uf2
