name: Build qmk on GitHub Actions

on:
  - push

env:
  KEYBOARD: 'kewbie/kewbie46_lili'
  KEYMAP: 'via'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone qmk/qmk_firmware
      uses: actions/checkout@v3
      with:
        repository: 'qmk/qmk_firmware'
        submodules: true
    - name: Install dependencies
      run: ./util/qmk_install.sh
    - name: build
      run: ~/.local/bin/qmk compile -kb ${{ env.KEYBOARD }} -km ${{ env.KEYMAP }}
    - uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: ./.build/*.uf2
